### ISSUE TITLE
SparkCompare Throwing NameError.

### ISSUE THREAD

**Issue by DeonBoon** [capitalone/datacompy#53]
Hi author, I am trying to use the SparkCompare functionality with the sample code that you have provided but it is throwing me this error:

```
Traceback (most recent call last):
  File ".\spark.py", line 69, in <module>
    comparison.report()
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 862, in report
    self._print_row_matches_by_column(file)
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 689, in _print_row_matches_by_column
    self._populate_columns_match_dict()
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 529, in _populate_columns_match_dict
    match_data = match_dataframe.agg(*[helper(col) for col in self.columns_compared]).collect()[
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 529, in <listcomp>
    match_data = match_dataframe.agg(*[helper(col) for col in self.columns_compared]).collect()[
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 523, in helper
    predicates = [F.col(c) == k.value for k in MatchType]
  File "C:\Users\\AppData\Roaming\Python\Python37\site-packages\datacompy\sparkcompare.py", line 523, in <listcomp>
    predicates = [F.col(c) == k.value for k in MatchType]
NameError: name 'F' is not defined
```

Any idea why is this happening? Thanks! :)

**Comment by DeonBoon** [comment]
Found out that sparkcompare.py wasn't able to locate my spark folder so i added these lines of code in sparkcompare.py

`import findspark
findspark.init('C:\spark\spark-2.4.4-bin-hadoop2.7')`
