### ISSUE TITLE
TypeError: an integer is required  - during import 

### ISSUE THREAD

**Issue by cabymetal** [capitalone/datacompy#89]
there is an error during import when I run 
`import datacompy`

this error arises
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\datacompy\__init__.py", line 20, in <module>
    from datacompy.sparkcompare import SparkCompare, NUMERIC_SPARK_TYPES
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\datacompy\sparkcompare.py", line 26, in <module>
    from pyspark.sql import functions as F
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\context.py", line 31, in <module>
    from pyspark import accumulators
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\serializers.py", line 72, in <module>
    from pyspark import cloudpickle
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pyspark\cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)`

I have another version of this library running on two different pc's but this error must be new

**Comment by cabymetal** [comment]
after reading the error I notices that it was a pyspark error not a datacompy error sorry
